// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.espread.sys.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Rdrecords08 implements Serializable {
    private Long autoid;
    private Long id;
    private String cinvcode;
    private BigDecimal inum;
    private BigDecimal iquantity;
    private BigDecimal iunitcost;
    private BigDecimal iprice;
    private BigDecimal iaprice;
    private BigDecimal ipunitcost;
    private BigDecimal ipprice;
    private String cbatch;
    private Long cvouchcode;
    private String cinvouchcode;
    private String cinvouchtype;
    private BigDecimal isoutquantity;
    private BigDecimal isoutnum;
    private String cfree1;
    private String cfree2;
    private Byte iflag;
    private Date dsdate;
    private BigDecimal itax;
    private BigDecimal isquantity;
    private BigDecimal isnum;
    private BigDecimal imoney;
    private BigDecimal ifnum;
    private BigDecimal ifquantity;
    private Date dvdate;
    private String cposition;
    private String cdefine22;
    private String cdefine23;
    private String cdefine24;
    private String cdefine25;
    private Double cdefine26;
    private Double cdefine27;
    private String citemClass;
    private String citemcode;
    private Long iposid;
    private BigDecimal facost;
    private String cname;
    private String citemcname;
    private String cfree3;
    private String cfree4;
    private String cfree5;
    private String cfree6;
    private String cfree7;
    private String cfree8;
    private String cfree9;
    private String cfree10;
    private String cbarcode;
    private BigDecimal inquantity;
    private BigDecimal innum;
    private String cassunit;
    private Date dmadedate;
    private Integer imassdate;
    private String cdefine28;
    private String cdefine29;
    private String cdefine30;
    private String cdefine31;
    private String cdefine32;
    private String cdefine33;
    private Integer cdefine34;
    private Integer cdefine35;
    private Date cdefine36;
    private Date cdefine37;
    private Long icheckids;
    private String cbvencode;
    private String chvencode;
    private Boolean bgsp;
    private String cgspstate;
    private Long iarrsid;
    private String ccheckcode;
    private Long icheckidbaks;
    private String crejectcode;
    private Long irejectids;
    private String ccheckpersoncode;
    private Date dcheckdate;
    private BigDecimal ioritaxcost;
    private BigDecimal ioricost;
    private BigDecimal iorimoney;
    private BigDecimal ioritaxprice;
    private BigDecimal iorisum;
    private BigDecimal itaxrate;
    private BigDecimal itaxprice;
    private BigDecimal isum;
    private Boolean btaxcost;
    private String cpoid;
    private Short cmassunit;
    private BigDecimal imaterialfee;
    private BigDecimal iprocesscost;
    private BigDecimal iprocessfee;
    private Date dmsdate;
    private BigDecimal ismaterialfee;
    private BigDecimal isprocessfee;
    private Integer iomodid;
    private String strcontractid;
    private String strcode;
    private Boolean bchecked;
    private Boolean brelated;
    private Long iomomid;
    private Integer imatsettlestate;
    private Integer ibillsettlecount;
    private Boolean blpusefree;
    private Long ioritrackid;
    private String coritracktype;
    private String cbaccounter;
    private Date dbkeepdate;
    private Boolean bcosting;
    private BigDecimal isumbillquantity;
    private Boolean bvmiused;
    private BigDecimal ivmisettlequantity;
    private BigDecimal ivmisettlenum;
    private String cvmivencode;
    private Integer iinvsncount;
    private String cwhpersoncode;
    private String cwhpersonname;
    private BigDecimal impcost;
    private Integer iimosid;
    private Integer iimbsid;
    private String cbarvcode;
    private String dbarvdate;
    private BigDecimal iinvexchrate;
    private String corufts;
    private String comcode;
    private String strcontractguid;
    private Short iexpiratdatecalcu;
    private String cexpirationdate;
    private Date dexpirationdate;
    private String cciqbookcode;
    private BigDecimal ibondedsumqty;
    private Byte iordertype;
    private Integer iorderdid;
    private String iordercode;
    private Integer iorderseq;
    private String isodid;
    private Byte isotype;
    private String csocode;
    private Integer isoseq;
    private BigDecimal cbatchproperty1;
    private BigDecimal cbatchproperty2;
    private BigDecimal cbatchproperty3;
    private BigDecimal cbatchproperty4;
    private BigDecimal cbatchproperty5;
    private String cbatchproperty6;
    private String cbatchproperty7;
    private String cbatchproperty8;
    private String cbatchproperty9;
    private Date cbatchproperty10;
    private String cbmemo;
    private BigDecimal ifaqty;
    private BigDecimal istax;
    private Integer irowno;
    private String strowguid;
    private BigDecimal ipreuseqty;
    private BigDecimal ipreuseinum;
    private Integer idebitids;
    private BigDecimal outcopiedquantity;
    private Integer ioldpartid;
    private BigDecimal foldquantity;
    private String cbsysbarcode;
    private Boolean bmergecheck;
    private Integer imergecheckautoid;
    private Byte bnoitemused;
    private String creworkmocode;
    private Integer ireworkmodetailsid;
    private Integer iproducttype;
    private String cmaininvcode;
    private Integer imainmodetailsid;
    private BigDecimal isharematerialfee;
    private String cplanlotcode;
    private Short bgift;
    private Short iposflag;
    private Integer gcsourceid;
    private Integer gcsourceids;
    private String gcupcardnum;
    private Integer gcupid;
    private Integer gcupids;
    private byte[] rowufts;
    private String cSNDefine1;
    private String cSNDefine2;
    private String cSNDefine3;
    private String cSNDefine4;
    private String cSNDefine5;
    private String cInvSN;
    private static final long serialVersionUID = 1L;

    public String getcSNDefine1() {
        return this.cSNDefine1;
    }

    public void setcSNDefine1(String cSNDefine1) {
        this.cSNDefine1 = cSNDefine1;
    }

    public String getcSNDefine2() {
        return this.cSNDefine2;
    }

    public void setcSNDefine2(String cSNDefine2) {
        this.cSNDefine2 = cSNDefine2;
    }

    public String getcSNDefine3() {
        return this.cSNDefine3;
    }

    public void setcSNDefine3(String cSNDefine3) {
        this.cSNDefine3 = cSNDefine3;
    }

    public String getcSNDefine4() {
        return this.cSNDefine4;
    }

    public void setcSNDefine4(String cSNDefine4) {
        this.cSNDefine4 = cSNDefine4;
    }

    public String getcSNDefine5() {
        return this.cSNDefine5;
    }

    public void setcSNDefine5(String cSNDefine5) {
        this.cSNDefine5 = cSNDefine5;
    }

    public String getcInvSN() {
        return this.cInvSN;
    }

    public void setcInvSN(String cInvSN) {
        this.cInvSN = cInvSN;
    }

    public Long getAutoid() {
        return this.autoid;
    }

    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCinvcode() {
        return this.cinvcode;
    }

    public void setCinvcode(String cinvcode) {
        this.cinvcode = cinvcode == null ? null : cinvcode.trim();
    }

    public BigDecimal getInum() {
        return this.inum;
    }

    public void setInum(BigDecimal inum) {
        this.inum = inum;
    }

    public BigDecimal getIquantity() {
        return this.iquantity;
    }

    public void setIquantity(BigDecimal iquantity) {
        this.iquantity = iquantity;
    }

    public BigDecimal getIunitcost() {
        return this.iunitcost;
    }

    public void setIunitcost(BigDecimal iunitcost) {
        this.iunitcost = iunitcost;
    }

    public BigDecimal getIprice() {
        return this.iprice;
    }

    public void setIprice(BigDecimal iprice) {
        this.iprice = iprice;
    }

    public BigDecimal getIaprice() {
        return this.iaprice;
    }

    public void setIaprice(BigDecimal iaprice) {
        this.iaprice = iaprice;
    }

    public BigDecimal getIpunitcost() {
        return this.ipunitcost;
    }

    public void setIpunitcost(BigDecimal ipunitcost) {
        this.ipunitcost = ipunitcost;
    }

    public BigDecimal getIpprice() {
        return this.ipprice;
    }

    public void setIpprice(BigDecimal ipprice) {
        this.ipprice = ipprice;
    }

    public String getCbatch() {
        return this.cbatch;
    }

    public void setCbatch(String cbatch) {
        this.cbatch = cbatch == null ? null : cbatch.trim();
    }

    public Long getCvouchcode() {
        return this.cvouchcode;
    }

    public void setCvouchcode(Long cvouchcode) {
        this.cvouchcode = cvouchcode;
    }

    public String getCinvouchcode() {
        return this.cinvouchcode;
    }

    public void setCinvouchcode(String cinvouchcode) {
        this.cinvouchcode = cinvouchcode == null ? null : cinvouchcode.trim();
    }

    public String getCinvouchtype() {
        return this.cinvouchtype;
    }

    public void setCinvouchtype(String cinvouchtype) {
        this.cinvouchtype = cinvouchtype == null ? null : cinvouchtype.trim();
    }

    public BigDecimal getIsoutquantity() {
        return this.isoutquantity;
    }

    public void setIsoutquantity(BigDecimal isoutquantity) {
        this.isoutquantity = isoutquantity;
    }

    public BigDecimal getIsoutnum() {
        return this.isoutnum;
    }

    public void setIsoutnum(BigDecimal isoutnum) {
        this.isoutnum = isoutnum;
    }

    public String getCfree1() {
        return this.cfree1;
    }

    public void setCfree1(String cfree1) {
        this.cfree1 = cfree1 == null ? null : cfree1.trim();
    }

    public String getCfree2() {
        return this.cfree2;
    }

    public void setCfree2(String cfree2) {
        this.cfree2 = cfree2 == null ? null : cfree2.trim();
    }

    public Byte getIflag() {
        return this.iflag;
    }

    public void setIflag(Byte iflag) {
        this.iflag = iflag;
    }

    public Date getDsdate() {
        return this.dsdate;
    }

    public void setDsdate(Date dsdate) {
        this.dsdate = dsdate;
    }

    public BigDecimal getItax() {
        return this.itax;
    }

    public void setItax(BigDecimal itax) {
        this.itax = itax;
    }

    public BigDecimal getIsquantity() {
        return this.isquantity;
    }

    public void setIsquantity(BigDecimal isquantity) {
        this.isquantity = isquantity;
    }

    public BigDecimal getIsnum() {
        return this.isnum;
    }

    public void setIsnum(BigDecimal isnum) {
        this.isnum = isnum;
    }

    public BigDecimal getImoney() {
        return this.imoney;
    }

    public void setImoney(BigDecimal imoney) {
        this.imoney = imoney;
    }

    public BigDecimal getIfnum() {
        return this.ifnum;
    }

    public void setIfnum(BigDecimal ifnum) {
        this.ifnum = ifnum;
    }

    public BigDecimal getIfquantity() {
        return this.ifquantity;
    }

    public void setIfquantity(BigDecimal ifquantity) {
        this.ifquantity = ifquantity;
    }

    public Date getDvdate() {
        return this.dvdate;
    }

    public void setDvdate(Date dvdate) {
        this.dvdate = dvdate;
    }

    public String getCposition() {
        return this.cposition;
    }

    public void setCposition(String cposition) {
        this.cposition = cposition == null ? null : cposition.trim();
    }

    public String getCdefine22() {
        return this.cdefine22;
    }

    public void setCdefine22(String cdefine22) {
        this.cdefine22 = cdefine22 == null ? null : cdefine22.trim();
    }

    public String getCdefine23() {
        return this.cdefine23;
    }

    public void setCdefine23(String cdefine23) {
        this.cdefine23 = cdefine23 == null ? null : cdefine23.trim();
    }

    public String getCdefine24() {
        return this.cdefine24;
    }

    public void setCdefine24(String cdefine24) {
        this.cdefine24 = cdefine24 == null ? null : cdefine24.trim();
    }

    public String getCdefine25() {
        return this.cdefine25;
    }

    public void setCdefine25(String cdefine25) {
        this.cdefine25 = cdefine25 == null ? null : cdefine25.trim();
    }

    public Double getCdefine26() {
        return this.cdefine26;
    }

    public void setCdefine26(Double cdefine26) {
        this.cdefine26 = cdefine26;
    }

    public Double getCdefine27() {
        return this.cdefine27;
    }

    public void setCdefine27(Double cdefine27) {
        this.cdefine27 = cdefine27;
    }

    public String getCitemClass() {
        return this.citemClass;
    }

    public void setCitemClass(String citemClass) {
        this.citemClass = citemClass == null ? null : citemClass.trim();
    }

    public String getCitemcode() {
        return this.citemcode;
    }

    public void setCitemcode(String citemcode) {
        this.citemcode = citemcode == null ? null : citemcode.trim();
    }

    public Long getIposid() {
        return this.iposid;
    }

    public void setIposid(Long iposid) {
        this.iposid = iposid;
    }

    public BigDecimal getFacost() {
        return this.facost;
    }

    public void setFacost(BigDecimal facost) {
        this.facost = facost;
    }

    public String getCname() {
        return this.cname;
    }

    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    public String getCitemcname() {
        return this.citemcname;
    }

    public void setCitemcname(String citemcname) {
        this.citemcname = citemcname == null ? null : citemcname.trim();
    }

    public String getCfree3() {
        return this.cfree3;
    }

    public void setCfree3(String cfree3) {
        this.cfree3 = cfree3 == null ? null : cfree3.trim();
    }

    public String getCfree4() {
        return this.cfree4;
    }

    public void setCfree4(String cfree4) {
        this.cfree4 = cfree4 == null ? null : cfree4.trim();
    }

    public String getCfree5() {
        return this.cfree5;
    }

    public void setCfree5(String cfree5) {
        this.cfree5 = cfree5 == null ? null : cfree5.trim();
    }

    public String getCfree6() {
        return this.cfree6;
    }

    public void setCfree6(String cfree6) {
        this.cfree6 = cfree6 == null ? null : cfree6.trim();
    }

    public String getCfree7() {
        return this.cfree7;
    }

    public void setCfree7(String cfree7) {
        this.cfree7 = cfree7 == null ? null : cfree7.trim();
    }

    public String getCfree8() {
        return this.cfree8;
    }

    public void setCfree8(String cfree8) {
        this.cfree8 = cfree8 == null ? null : cfree8.trim();
    }

    public String getCfree9() {
        return this.cfree9;
    }

    public void setCfree9(String cfree9) {
        this.cfree9 = cfree9 == null ? null : cfree9.trim();
    }

    public String getCfree10() {
        return this.cfree10;
    }

    public void setCfree10(String cfree10) {
        this.cfree10 = cfree10 == null ? null : cfree10.trim();
    }

    public String getCbarcode() {
        return this.cbarcode;
    }

    public void setCbarcode(String cbarcode) {
        this.cbarcode = cbarcode == null ? null : cbarcode.trim();
    }

    public BigDecimal getInquantity() {
        return this.inquantity;
    }

    public void setInquantity(BigDecimal inquantity) {
        this.inquantity = inquantity;
    }

    public BigDecimal getInnum() {
        return this.innum;
    }

    public void setInnum(BigDecimal innum) {
        this.innum = innum;
    }

    public String getCassunit() {
        return this.cassunit;
    }

    public void setCassunit(String cassunit) {
        this.cassunit = cassunit == null ? null : cassunit.trim();
    }

    public Date getDmadedate() {
        return this.dmadedate;
    }

    public void setDmadedate(Date dmadedate) {
        this.dmadedate = dmadedate;
    }

    public Integer getImassdate() {
        return this.imassdate;
    }

    public void setImassdate(Integer imassdate) {
        this.imassdate = imassdate;
    }

    public String getCdefine28() {
        return this.cdefine28;
    }

    public void setCdefine28(String cdefine28) {
        this.cdefine28 = cdefine28 == null ? null : cdefine28.trim();
    }

    public String getCdefine29() {
        return this.cdefine29;
    }

    public void setCdefine29(String cdefine29) {
        this.cdefine29 = cdefine29 == null ? null : cdefine29.trim();
    }

    public String getCdefine30() {
        return this.cdefine30;
    }

    public void setCdefine30(String cdefine30) {
        this.cdefine30 = cdefine30 == null ? null : cdefine30.trim();
    }

    public String getCdefine31() {
        return this.cdefine31;
    }

    public void setCdefine31(String cdefine31) {
        this.cdefine31 = cdefine31 == null ? null : cdefine31.trim();
    }

    public String getCdefine32() {
        return this.cdefine32;
    }

    public void setCdefine32(String cdefine32) {
        this.cdefine32 = cdefine32 == null ? null : cdefine32.trim();
    }

    public String getCdefine33() {
        return this.cdefine33;
    }

    public void setCdefine33(String cdefine33) {
        this.cdefine33 = cdefine33 == null ? null : cdefine33.trim();
    }

    public Integer getCdefine34() {
        return this.cdefine34;
    }

    public void setCdefine34(Integer cdefine34) {
        this.cdefine34 = cdefine34;
    }

    public Integer getCdefine35() {
        return this.cdefine35;
    }

    public void setCdefine35(Integer cdefine35) {
        this.cdefine35 = cdefine35;
    }

    public Date getCdefine36() {
        return this.cdefine36;
    }

    public void setCdefine36(Date cdefine36) {
        this.cdefine36 = cdefine36;
    }

    public Date getCdefine37() {
        return this.cdefine37;
    }

    public void setCdefine37(Date cdefine37) {
        this.cdefine37 = cdefine37;
    }

    public Long getIcheckids() {
        return this.icheckids;
    }

    public void setIcheckids(Long icheckids) {
        this.icheckids = icheckids;
    }

    public String getCbvencode() {
        return this.cbvencode;
    }

    public void setCbvencode(String cbvencode) {
        this.cbvencode = cbvencode == null ? null : cbvencode.trim();
    }

    public String getChvencode() {
        return this.chvencode;
    }

    public void setChvencode(String chvencode) {
        this.chvencode = chvencode == null ? null : chvencode.trim();
    }

    public Boolean getBgsp() {
        return this.bgsp;
    }

    public void setBgsp(Boolean bgsp) {
        this.bgsp = bgsp;
    }

    public String getCgspstate() {
        return this.cgspstate;
    }

    public void setCgspstate(String cgspstate) {
        this.cgspstate = cgspstate == null ? null : cgspstate.trim();
    }

    public Long getIarrsid() {
        return this.iarrsid;
    }

    public void setIarrsid(Long iarrsid) {
        this.iarrsid = iarrsid;
    }

    public String getCcheckcode() {
        return this.ccheckcode;
    }

    public void setCcheckcode(String ccheckcode) {
        this.ccheckcode = ccheckcode == null ? null : ccheckcode.trim();
    }

    public Long getIcheckidbaks() {
        return this.icheckidbaks;
    }

    public void setIcheckidbaks(Long icheckidbaks) {
        this.icheckidbaks = icheckidbaks;
    }

    public String getCrejectcode() {
        return this.crejectcode;
    }

    public void setCrejectcode(String crejectcode) {
        this.crejectcode = crejectcode == null ? null : crejectcode.trim();
    }

    public Long getIrejectids() {
        return this.irejectids;
    }

    public void setIrejectids(Long irejectids) {
        this.irejectids = irejectids;
    }

    public String getCcheckpersoncode() {
        return this.ccheckpersoncode;
    }

    public void setCcheckpersoncode(String ccheckpersoncode) {
        this.ccheckpersoncode = ccheckpersoncode == null ? null : ccheckpersoncode.trim();
    }

    public Date getDcheckdate() {
        return this.dcheckdate;
    }

    public void setDcheckdate(Date dcheckdate) {
        this.dcheckdate = dcheckdate;
    }

    public BigDecimal getIoritaxcost() {
        return this.ioritaxcost;
    }

    public void setIoritaxcost(BigDecimal ioritaxcost) {
        this.ioritaxcost = ioritaxcost;
    }

    public BigDecimal getIoricost() {
        return this.ioricost;
    }

    public void setIoricost(BigDecimal ioricost) {
        this.ioricost = ioricost;
    }

    public BigDecimal getIorimoney() {
        return this.iorimoney;
    }

    public void setIorimoney(BigDecimal iorimoney) {
        this.iorimoney = iorimoney;
    }

    public BigDecimal getIoritaxprice() {
        return this.ioritaxprice;
    }

    public void setIoritaxprice(BigDecimal ioritaxprice) {
        this.ioritaxprice = ioritaxprice;
    }

    public BigDecimal getIorisum() {
        return this.iorisum;
    }

    public void setIorisum(BigDecimal iorisum) {
        this.iorisum = iorisum;
    }

    public BigDecimal getItaxrate() {
        return this.itaxrate;
    }

    public void setItaxrate(BigDecimal itaxrate) {
        this.itaxrate = itaxrate;
    }

    public BigDecimal getItaxprice() {
        return this.itaxprice;
    }

    public void setItaxprice(BigDecimal itaxprice) {
        this.itaxprice = itaxprice;
    }

    public BigDecimal getIsum() {
        return this.isum;
    }

    public void setIsum(BigDecimal isum) {
        this.isum = isum;
    }

    public Boolean getBtaxcost() {
        return this.btaxcost;
    }

    public void setBtaxcost(Boolean btaxcost) {
        this.btaxcost = btaxcost;
    }

    public String getCpoid() {
        return this.cpoid;
    }

    public void setCpoid(String cpoid) {
        this.cpoid = cpoid == null ? null : cpoid.trim();
    }

    public Short getCmassunit() {
        return this.cmassunit;
    }

    public void setCmassunit(Short cmassunit) {
        this.cmassunit = cmassunit;
    }

    public BigDecimal getImaterialfee() {
        return this.imaterialfee;
    }

    public void setImaterialfee(BigDecimal imaterialfee) {
        this.imaterialfee = imaterialfee;
    }

    public BigDecimal getIprocesscost() {
        return this.iprocesscost;
    }

    public void setIprocesscost(BigDecimal iprocesscost) {
        this.iprocesscost = iprocesscost;
    }

    public BigDecimal getIprocessfee() {
        return this.iprocessfee;
    }

    public void setIprocessfee(BigDecimal iprocessfee) {
        this.iprocessfee = iprocessfee;
    }

    public Date getDmsdate() {
        return this.dmsdate;
    }

    public void setDmsdate(Date dmsdate) {
        this.dmsdate = dmsdate;
    }

    public BigDecimal getIsmaterialfee() {
        return this.ismaterialfee;
    }

    public void setIsmaterialfee(BigDecimal ismaterialfee) {
        this.ismaterialfee = ismaterialfee;
    }

    public BigDecimal getIsprocessfee() {
        return this.isprocessfee;
    }

    public void setIsprocessfee(BigDecimal isprocessfee) {
        this.isprocessfee = isprocessfee;
    }

    public Integer getIomodid() {
        return this.iomodid;
    }

    public void setIomodid(Integer iomodid) {
        this.iomodid = iomodid;
    }

    public String getStrcontractid() {
        return this.strcontractid;
    }

    public void setStrcontractid(String strcontractid) {
        this.strcontractid = strcontractid == null ? null : strcontractid.trim();
    }

    public String getStrcode() {
        return this.strcode;
    }

    public void setStrcode(String strcode) {
        this.strcode = strcode == null ? null : strcode.trim();
    }

    public Boolean getBchecked() {
        return this.bchecked;
    }

    public void setBchecked(Boolean bchecked) {
        this.bchecked = bchecked;
    }

    public Boolean getBrelated() {
        return this.brelated;
    }

    public void setBrelated(Boolean brelated) {
        this.brelated = brelated;
    }

    public Long getIomomid() {
        return this.iomomid;
    }

    public void setIomomid(Long iomomid) {
        this.iomomid = iomomid;
    }

    public Integer getImatsettlestate() {
        return this.imatsettlestate;
    }

    public void setImatsettlestate(Integer imatsettlestate) {
        this.imatsettlestate = imatsettlestate;
    }

    public Integer getIbillsettlecount() {
        return this.ibillsettlecount;
    }

    public void setIbillsettlecount(Integer ibillsettlecount) {
        this.ibillsettlecount = ibillsettlecount;
    }

    public Boolean getBlpusefree() {
        return this.blpusefree;
    }

    public void setBlpusefree(Boolean blpusefree) {
        this.blpusefree = blpusefree;
    }

    public Long getIoritrackid() {
        return this.ioritrackid;
    }

    public void setIoritrackid(Long ioritrackid) {
        this.ioritrackid = ioritrackid;
    }

    public String getCoritracktype() {
        return this.coritracktype;
    }

    public void setCoritracktype(String coritracktype) {
        this.coritracktype = coritracktype == null ? null : coritracktype.trim();
    }

    public String getCbaccounter() {
        return this.cbaccounter;
    }

    public void setCbaccounter(String cbaccounter) {
        this.cbaccounter = cbaccounter == null ? null : cbaccounter.trim();
    }

    public Date getDbkeepdate() {
        return this.dbkeepdate;
    }

    public void setDbkeepdate(Date dbkeepdate) {
        this.dbkeepdate = dbkeepdate;
    }

    public Boolean getBcosting() {
        return this.bcosting;
    }

    public void setBcosting(Boolean bcosting) {
        this.bcosting = bcosting;
    }

    public BigDecimal getIsumbillquantity() {
        return this.isumbillquantity;
    }

    public void setIsumbillquantity(BigDecimal isumbillquantity) {
        this.isumbillquantity = isumbillquantity;
    }

    public Boolean getBvmiused() {
        return this.bvmiused;
    }

    public void setBvmiused(Boolean bvmiused) {
        this.bvmiused = bvmiused;
    }

    public BigDecimal getIvmisettlequantity() {
        return this.ivmisettlequantity;
    }

    public void setIvmisettlequantity(BigDecimal ivmisettlequantity) {
        this.ivmisettlequantity = ivmisettlequantity;
    }

    public BigDecimal getIvmisettlenum() {
        return this.ivmisettlenum;
    }

    public void setIvmisettlenum(BigDecimal ivmisettlenum) {
        this.ivmisettlenum = ivmisettlenum;
    }

    public String getCvmivencode() {
        return this.cvmivencode;
    }

    public void setCvmivencode(String cvmivencode) {
        this.cvmivencode = cvmivencode == null ? null : cvmivencode.trim();
    }

    public Integer getIinvsncount() {
        return this.iinvsncount;
    }

    public void setIinvsncount(Integer iinvsncount) {
        this.iinvsncount = iinvsncount;
    }

    public String getCwhpersoncode() {
        return this.cwhpersoncode;
    }

    public void setCwhpersoncode(String cwhpersoncode) {
        this.cwhpersoncode = cwhpersoncode == null ? null : cwhpersoncode.trim();
    }

    public String getCwhpersonname() {
        return this.cwhpersonname;
    }

    public void setCwhpersonname(String cwhpersonname) {
        this.cwhpersonname = cwhpersonname == null ? null : cwhpersonname.trim();
    }

    public BigDecimal getImpcost() {
        return this.impcost;
    }

    public void setImpcost(BigDecimal impcost) {
        this.impcost = impcost;
    }

    public Integer getIimosid() {
        return this.iimosid;
    }

    public void setIimosid(Integer iimosid) {
        this.iimosid = iimosid;
    }

    public Integer getIimbsid() {
        return this.iimbsid;
    }

    public void setIimbsid(Integer iimbsid) {
        this.iimbsid = iimbsid;
    }

    public String getCbarvcode() {
        return this.cbarvcode;
    }

    public void setCbarvcode(String cbarvcode) {
        this.cbarvcode = cbarvcode == null ? null : cbarvcode.trim();
    }

    public String getDbarvdate() {
        return this.dbarvdate;
    }

    public void setDbarvdate(String dbarvdate) {
        this.dbarvdate = dbarvdate == null ? null : dbarvdate.trim();
    }

    public BigDecimal getIinvexchrate() {
        return this.iinvexchrate;
    }

    public void setIinvexchrate(BigDecimal iinvexchrate) {
        this.iinvexchrate = iinvexchrate;
    }

    public String getCorufts() {
        return this.corufts;
    }

    public void setCorufts(String corufts) {
        this.corufts = corufts == null ? null : corufts.trim();
    }

    public String getComcode() {
        return this.comcode;
    }

    public void setComcode(String comcode) {
        this.comcode = comcode == null ? null : comcode.trim();
    }

    public String getStrcontractguid() {
        return this.strcontractguid;
    }

    public void setStrcontractguid(String strcontractguid) {
        this.strcontractguid = strcontractguid == null ? null : strcontractguid.trim();
    }

    public Short getIexpiratdatecalcu() {
        return this.iexpiratdatecalcu;
    }

    public void setIexpiratdatecalcu(Short iexpiratdatecalcu) {
        this.iexpiratdatecalcu = iexpiratdatecalcu;
    }

    public String getCexpirationdate() {
        return this.cexpirationdate;
    }

    public void setCexpirationdate(String cexpirationdate) {
        this.cexpirationdate = cexpirationdate == null ? null : cexpirationdate.trim();
    }

    public Date getDexpirationdate() {
        return this.dexpirationdate;
    }

    public void setDexpirationdate(Date dexpirationdate) {
        this.dexpirationdate = dexpirationdate;
    }

    public String getCciqbookcode() {
        return this.cciqbookcode;
    }

    public void setCciqbookcode(String cciqbookcode) {
        this.cciqbookcode = cciqbookcode == null ? null : cciqbookcode.trim();
    }

    public BigDecimal getIbondedsumqty() {
        return this.ibondedsumqty;
    }

    public void setIbondedsumqty(BigDecimal ibondedsumqty) {
        this.ibondedsumqty = ibondedsumqty;
    }

    public Byte getIordertype() {
        return this.iordertype;
    }

    public void setIordertype(Byte iordertype) {
        this.iordertype = iordertype;
    }

    public Integer getIorderdid() {
        return this.iorderdid;
    }

    public void setIorderdid(Integer iorderdid) {
        this.iorderdid = iorderdid;
    }

    public String getIordercode() {
        return this.iordercode;
    }

    public void setIordercode(String iordercode) {
        this.iordercode = iordercode == null ? null : iordercode.trim();
    }

    public Integer getIorderseq() {
        return this.iorderseq;
    }

    public void setIorderseq(Integer iorderseq) {
        this.iorderseq = iorderseq;
    }

    public String getIsodid() {
        return this.isodid;
    }

    public void setIsodid(String isodid) {
        this.isodid = isodid == null ? null : isodid.trim();
    }

    public Byte getIsotype() {
        return this.isotype;
    }

    public void setIsotype(Byte isotype) {
        this.isotype = isotype;
    }

    public String getCsocode() {
        return this.csocode;
    }

    public void setCsocode(String csocode) {
        this.csocode = csocode == null ? null : csocode.trim();
    }

    public Integer getIsoseq() {
        return this.isoseq;
    }

    public void setIsoseq(Integer isoseq) {
        this.isoseq = isoseq;
    }

    public BigDecimal getCbatchproperty1() {
        return this.cbatchproperty1;
    }

    public void setCbatchproperty1(BigDecimal cbatchproperty1) {
        this.cbatchproperty1 = cbatchproperty1;
    }

    public BigDecimal getCbatchproperty2() {
        return this.cbatchproperty2;
    }

    public void setCbatchproperty2(BigDecimal cbatchproperty2) {
        this.cbatchproperty2 = cbatchproperty2;
    }

    public BigDecimal getCbatchproperty3() {
        return this.cbatchproperty3;
    }

    public void setCbatchproperty3(BigDecimal cbatchproperty3) {
        this.cbatchproperty3 = cbatchproperty3;
    }

    public BigDecimal getCbatchproperty4() {
        return this.cbatchproperty4;
    }

    public void setCbatchproperty4(BigDecimal cbatchproperty4) {
        this.cbatchproperty4 = cbatchproperty4;
    }

    public BigDecimal getCbatchproperty5() {
        return this.cbatchproperty5;
    }

    public void setCbatchproperty5(BigDecimal cbatchproperty5) {
        this.cbatchproperty5 = cbatchproperty5;
    }

    public String getCbatchproperty6() {
        return this.cbatchproperty6;
    }

    public void setCbatchproperty6(String cbatchproperty6) {
        this.cbatchproperty6 = cbatchproperty6 == null ? null : cbatchproperty6.trim();
    }

    public String getCbatchproperty7() {
        return this.cbatchproperty7;
    }

    public void setCbatchproperty7(String cbatchproperty7) {
        this.cbatchproperty7 = cbatchproperty7 == null ? null : cbatchproperty7.trim();
    }

    public String getCbatchproperty8() {
        return this.cbatchproperty8;
    }

    public void setCbatchproperty8(String cbatchproperty8) {
        this.cbatchproperty8 = cbatchproperty8 == null ? null : cbatchproperty8.trim();
    }

    public String getCbatchproperty9() {
        return this.cbatchproperty9;
    }

    public void setCbatchproperty9(String cbatchproperty9) {
        this.cbatchproperty9 = cbatchproperty9 == null ? null : cbatchproperty9.trim();
    }

    public Date getCbatchproperty10() {
        return this.cbatchproperty10;
    }

    public void setCbatchproperty10(Date cbatchproperty10) {
        this.cbatchproperty10 = cbatchproperty10;
    }

    public String getCbmemo() {
        return this.cbmemo;
    }

    public void setCbmemo(String cbmemo) {
        this.cbmemo = cbmemo == null ? null : cbmemo.trim();
    }

    public BigDecimal getIfaqty() {
        return this.ifaqty;
    }

    public void setIfaqty(BigDecimal ifaqty) {
        this.ifaqty = ifaqty;
    }

    public BigDecimal getIstax() {
        return this.istax;
    }

    public void setIstax(BigDecimal istax) {
        this.istax = istax;
    }

    public Integer getIrowno() {
        return this.irowno;
    }

    public void setIrowno(Integer irowno) {
        this.irowno = irowno;
    }

    public String getStrowguid() {
        return this.strowguid;
    }

    public void setStrowguid(String strowguid) {
        this.strowguid = strowguid == null ? null : strowguid.trim();
    }

    public BigDecimal getIpreuseqty() {
        return this.ipreuseqty;
    }

    public void setIpreuseqty(BigDecimal ipreuseqty) {
        this.ipreuseqty = ipreuseqty;
    }

    public BigDecimal getIpreuseinum() {
        return this.ipreuseinum;
    }

    public void setIpreuseinum(BigDecimal ipreuseinum) {
        this.ipreuseinum = ipreuseinum;
    }

    public Integer getIdebitids() {
        return this.idebitids;
    }

    public void setIdebitids(Integer idebitids) {
        this.idebitids = idebitids;
    }

    public BigDecimal getOutcopiedquantity() {
        return this.outcopiedquantity;
    }

    public void setOutcopiedquantity(BigDecimal outcopiedquantity) {
        this.outcopiedquantity = outcopiedquantity;
    }

    public Integer getIoldpartid() {
        return this.ioldpartid;
    }

    public void setIoldpartid(Integer ioldpartid) {
        this.ioldpartid = ioldpartid;
    }

    public BigDecimal getFoldquantity() {
        return this.foldquantity;
    }

    public void setFoldquantity(BigDecimal foldquantity) {
        this.foldquantity = foldquantity;
    }

    public String getCbsysbarcode() {
        return this.cbsysbarcode;
    }

    public void setCbsysbarcode(String cbsysbarcode) {
        this.cbsysbarcode = cbsysbarcode == null ? null : cbsysbarcode.trim();
    }

    public Boolean getBmergecheck() {
        return this.bmergecheck;
    }

    public void setBmergecheck(Boolean bmergecheck) {
        this.bmergecheck = bmergecheck;
    }

    public Integer getImergecheckautoid() {
        return this.imergecheckautoid;
    }

    public void setImergecheckautoid(Integer imergecheckautoid) {
        this.imergecheckautoid = imergecheckautoid;
    }

    public Byte getBnoitemused() {
        return this.bnoitemused;
    }

    public void setBnoitemused(Byte bnoitemused) {
        this.bnoitemused = bnoitemused;
    }

    public String getCreworkmocode() {
        return this.creworkmocode;
    }

    public void setCreworkmocode(String creworkmocode) {
        this.creworkmocode = creworkmocode == null ? null : creworkmocode.trim();
    }

    public Integer getIreworkmodetailsid() {
        return this.ireworkmodetailsid;
    }

    public void setIreworkmodetailsid(Integer ireworkmodetailsid) {
        this.ireworkmodetailsid = ireworkmodetailsid;
    }

    public Integer getIproducttype() {
        return this.iproducttype;
    }

    public void setIproducttype(Integer iproducttype) {
        this.iproducttype = iproducttype;
    }

    public String getCmaininvcode() {
        return this.cmaininvcode;
    }

    public void setCmaininvcode(String cmaininvcode) {
        this.cmaininvcode = cmaininvcode == null ? null : cmaininvcode.trim();
    }

    public Integer getImainmodetailsid() {
        return this.imainmodetailsid;
    }

    public void setImainmodetailsid(Integer imainmodetailsid) {
        this.imainmodetailsid = imainmodetailsid;
    }

    public BigDecimal getIsharematerialfee() {
        return this.isharematerialfee;
    }

    public void setIsharematerialfee(BigDecimal isharematerialfee) {
        this.isharematerialfee = isharematerialfee;
    }

    public String getCplanlotcode() {
        return this.cplanlotcode;
    }

    public void setCplanlotcode(String cplanlotcode) {
        this.cplanlotcode = cplanlotcode == null ? null : cplanlotcode.trim();
    }

    public Short getBgift() {
        return this.bgift;
    }

    public void setBgift(Short bgift) {
        this.bgift = bgift;
    }

    public Short getIposflag() {
        return this.iposflag;
    }

    public void setIposflag(Short iposflag) {
        this.iposflag = iposflag;
    }

    public Integer getGcsourceid() {
        return this.gcsourceid;
    }

    public void setGcsourceid(Integer gcsourceid) {
        this.gcsourceid = gcsourceid;
    }

    public Integer getGcsourceids() {
        return this.gcsourceids;
    }

    public void setGcsourceids(Integer gcsourceids) {
        this.gcsourceids = gcsourceids;
    }

    public String getGcupcardnum() {
        return this.gcupcardnum;
    }

    public void setGcupcardnum(String gcupcardnum) {
        this.gcupcardnum = gcupcardnum == null ? null : gcupcardnum.trim();
    }

    public Integer getGcupid() {
        return this.gcupid;
    }

    public void setGcupid(Integer gcupid) {
        this.gcupid = gcupid;
    }

    public Integer getGcupids() {
        return this.gcupids;
    }

    public void setGcupids(Integer gcupids) {
        this.gcupids = gcupids;
    }

    public byte[] getRowufts() {
        return this.rowufts;
    }

    public void setRowufts(byte[] rowufts) {
        this.rowufts = rowufts;
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(this.getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(this.hashCode());
        sb.append(", autoid=").append(this.autoid);
        sb.append(", id=").append(this.id);
        sb.append(", cinvcode=").append(this.cinvcode);
        sb.append(", inum=").append(this.inum);
        sb.append(", iquantity=").append(this.iquantity);
        sb.append(", iunitcost=").append(this.iunitcost);
        sb.append(", iprice=").append(this.iprice);
        sb.append(", iaprice=").append(this.iaprice);
        sb.append(", ipunitcost=").append(this.ipunitcost);
        sb.append(", ipprice=").append(this.ipprice);
        sb.append(", cbatch=").append(this.cbatch);
        sb.append(", cvouchcode=").append(this.cvouchcode);
        sb.append(", cinvouchcode=").append(this.cinvouchcode);
        sb.append(", cinvouchtype=").append(this.cinvouchtype);
        sb.append(", isoutquantity=").append(this.isoutquantity);
        sb.append(", isoutnum=").append(this.isoutnum);
        sb.append(", cfree1=").append(this.cfree1);
        sb.append(", cfree2=").append(this.cfree2);
        sb.append(", iflag=").append(this.iflag);
        sb.append(", dsdate=").append(this.dsdate);
        sb.append(", itax=").append(this.itax);
        sb.append(", isquantity=").append(this.isquantity);
        sb.append(", isnum=").append(this.isnum);
        sb.append(", imoney=").append(this.imoney);
        sb.append(", ifnum=").append(this.ifnum);
        sb.append(", ifquantity=").append(this.ifquantity);
        sb.append(", dvdate=").append(this.dvdate);
        sb.append(", cposition=").append(this.cposition);
        sb.append(", cdefine22=").append(this.cdefine22);
        sb.append(", cdefine23=").append(this.cdefine23);
        sb.append(", cdefine24=").append(this.cdefine24);
        sb.append(", cdefine25=").append(this.cdefine25);
        sb.append(", cdefine26=").append(this.cdefine26);
        sb.append(", cdefine27=").append(this.cdefine27);
        sb.append(", citemClass=").append(this.citemClass);
        sb.append(", citemcode=").append(this.citemcode);
        sb.append(", iposid=").append(this.iposid);
        sb.append(", facost=").append(this.facost);
        sb.append(", cname=").append(this.cname);
        sb.append(", citemcname=").append(this.citemcname);
        sb.append(", cfree3=").append(this.cfree3);
        sb.append(", cfree4=").append(this.cfree4);
        sb.append(", cfree5=").append(this.cfree5);
        sb.append(", cfree6=").append(this.cfree6);
        sb.append(", cfree7=").append(this.cfree7);
        sb.append(", cfree8=").append(this.cfree8);
        sb.append(", cfree9=").append(this.cfree9);
        sb.append(", cfree10=").append(this.cfree10);
        sb.append(", cbarcode=").append(this.cbarcode);
        sb.append(", inquantity=").append(this.inquantity);
        sb.append(", innum=").append(this.innum);
        sb.append(", cassunit=").append(this.cassunit);
        sb.append(", dmadedate=").append(this.dmadedate);
        sb.append(", imassdate=").append(this.imassdate);
        sb.append(", cdefine28=").append(this.cdefine28);
        sb.append(", cdefine29=").append(this.cdefine29);
        sb.append(", cdefine30=").append(this.cdefine30);
        sb.append(", cdefine31=").append(this.cdefine31);
        sb.append(", cdefine32=").append(this.cdefine32);
        sb.append(", cdefine33=").append(this.cdefine33);
        sb.append(", cdefine34=").append(this.cdefine34);
        sb.append(", cdefine35=").append(this.cdefine35);
        sb.append(", cdefine36=").append(this.cdefine36);
        sb.append(", cdefine37=").append(this.cdefine37);
        sb.append(", icheckids=").append(this.icheckids);
        sb.append(", cbvencode=").append(this.cbvencode);
        sb.append(", chvencode=").append(this.chvencode);
        sb.append(", bgsp=").append(this.bgsp);
        sb.append(", cgspstate=").append(this.cgspstate);
        sb.append(", iarrsid=").append(this.iarrsid);
        sb.append(", ccheckcode=").append(this.ccheckcode);
        sb.append(", icheckidbaks=").append(this.icheckidbaks);
        sb.append(", crejectcode=").append(this.crejectcode);
        sb.append(", irejectids=").append(this.irejectids);
        sb.append(", ccheckpersoncode=").append(this.ccheckpersoncode);
        sb.append(", dcheckdate=").append(this.dcheckdate);
        sb.append(", ioritaxcost=").append(this.ioritaxcost);
        sb.append(", ioricost=").append(this.ioricost);
        sb.append(", iorimoney=").append(this.iorimoney);
        sb.append(", ioritaxprice=").append(this.ioritaxprice);
        sb.append(", iorisum=").append(this.iorisum);
        sb.append(", itaxrate=").append(this.itaxrate);
        sb.append(", itaxprice=").append(this.itaxprice);
        sb.append(", isum=").append(this.isum);
        sb.append(", btaxcost=").append(this.btaxcost);
        sb.append(", cpoid=").append(this.cpoid);
        sb.append(", cmassunit=").append(this.cmassunit);
        sb.append(", imaterialfee=").append(this.imaterialfee);
        sb.append(", iprocesscost=").append(this.iprocesscost);
        sb.append(", iprocessfee=").append(this.iprocessfee);
        sb.append(", dmsdate=").append(this.dmsdate);
        sb.append(", ismaterialfee=").append(this.ismaterialfee);
        sb.append(", isprocessfee=").append(this.isprocessfee);
        sb.append(", iomodid=").append(this.iomodid);
        sb.append(", strcontractid=").append(this.strcontractid);
        sb.append(", strcode=").append(this.strcode);
        sb.append(", bchecked=").append(this.bchecked);
        sb.append(", brelated=").append(this.brelated);
        sb.append(", iomomid=").append(this.iomomid);
        sb.append(", imatsettlestate=").append(this.imatsettlestate);
        sb.append(", ibillsettlecount=").append(this.ibillsettlecount);
        sb.append(", blpusefree=").append(this.blpusefree);
        sb.append(", ioritrackid=").append(this.ioritrackid);
        sb.append(", coritracktype=").append(this.coritracktype);
        sb.append(", cbaccounter=").append(this.cbaccounter);
        sb.append(", dbkeepdate=").append(this.dbkeepdate);
        sb.append(", bcosting=").append(this.bcosting);
        sb.append(", isumbillquantity=").append(this.isumbillquantity);
        sb.append(", bvmiused=").append(this.bvmiused);
        sb.append(", ivmisettlequantity=").append(this.ivmisettlequantity);
        sb.append(", ivmisettlenum=").append(this.ivmisettlenum);
        sb.append(", cvmivencode=").append(this.cvmivencode);
        sb.append(", iinvsncount=").append(this.iinvsncount);
        sb.append(", cwhpersoncode=").append(this.cwhpersoncode);
        sb.append(", cwhpersonname=").append(this.cwhpersonname);
        sb.append(", impcost=").append(this.impcost);
        sb.append(", iimosid=").append(this.iimosid);
        sb.append(", iimbsid=").append(this.iimbsid);
        sb.append(", cbarvcode=").append(this.cbarvcode);
        sb.append(", dbarvdate=").append(this.dbarvdate);
        sb.append(", iinvexchrate=").append(this.iinvexchrate);
        sb.append(", corufts=").append(this.corufts);
        sb.append(", comcode=").append(this.comcode);
        sb.append(", strcontractguid=").append(this.strcontractguid);
        sb.append(", iexpiratdatecalcu=").append(this.iexpiratdatecalcu);
        sb.append(", cexpirationdate=").append(this.cexpirationdate);
        sb.append(", dexpirationdate=").append(this.dexpirationdate);
        sb.append(", cciqbookcode=").append(this.cciqbookcode);
        sb.append(", ibondedsumqty=").append(this.ibondedsumqty);
        sb.append(", iordertype=").append(this.iordertype);
        sb.append(", iorderdid=").append(this.iorderdid);
        sb.append(", iordercode=").append(this.iordercode);
        sb.append(", iorderseq=").append(this.iorderseq);
        sb.append(", isodid=").append(this.isodid);
        sb.append(", isotype=").append(this.isotype);
        sb.append(", csocode=").append(this.csocode);
        sb.append(", isoseq=").append(this.isoseq);
        sb.append(", cbatchproperty1=").append(this.cbatchproperty1);
        sb.append(", cbatchproperty2=").append(this.cbatchproperty2);
        sb.append(", cbatchproperty3=").append(this.cbatchproperty3);
        sb.append(", cbatchproperty4=").append(this.cbatchproperty4);
        sb.append(", cbatchproperty5=").append(this.cbatchproperty5);
        sb.append(", cbatchproperty6=").append(this.cbatchproperty6);
        sb.append(", cbatchproperty7=").append(this.cbatchproperty7);
        sb.append(", cbatchproperty8=").append(this.cbatchproperty8);
        sb.append(", cbatchproperty9=").append(this.cbatchproperty9);
        sb.append(", cbatchproperty10=").append(this.cbatchproperty10);
        sb.append(", cbmemo=").append(this.cbmemo);
        sb.append(", ifaqty=").append(this.ifaqty);
        sb.append(", istax=").append(this.istax);
        sb.append(", irowno=").append(this.irowno);
        sb.append(", strowguid=").append(this.strowguid);
        sb.append(", ipreuseqty=").append(this.ipreuseqty);
        sb.append(", ipreuseinum=").append(this.ipreuseinum);
        sb.append(", idebitids=").append(this.idebitids);
        sb.append(", outcopiedquantity=").append(this.outcopiedquantity);
        sb.append(", ioldpartid=").append(this.ioldpartid);
        sb.append(", foldquantity=").append(this.foldquantity);
        sb.append(", cbsysbarcode=").append(this.cbsysbarcode);
        sb.append(", bmergecheck=").append(this.bmergecheck);
        sb.append(", imergecheckautoid=").append(this.imergecheckautoid);
        sb.append(", bnoitemused=").append(this.bnoitemused);
        sb.append(", creworkmocode=").append(this.creworkmocode);
        sb.append(", ireworkmodetailsid=").append(this.ireworkmodetailsid);
        sb.append(", iproducttype=").append(this.iproducttype);
        sb.append(", cmaininvcode=").append(this.cmaininvcode);
        sb.append(", imainmodetailsid=").append(this.imainmodetailsid);
        sb.append(", isharematerialfee=").append(this.isharematerialfee);
        sb.append(", cplanlotcode=").append(this.cplanlotcode);
        sb.append(", bgift=").append(this.bgift);
        sb.append(", iposflag=").append(this.iposflag);
        sb.append(", gcsourceid=").append(this.gcsourceid);
        sb.append(", gcsourceids=").append(this.gcsourceids);
        sb.append(", gcupcardnum=").append(this.gcupcardnum);
        sb.append(", gcupid=").append(this.gcupid);
        sb.append(", gcupids=").append(this.gcupids);
        sb.append(", rowufts=").append(this.rowufts);
        sb.append(", serialVersionUID=").append(1L);
        sb.append("]");
        return sb.toString();
    }
}
